apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-7gfl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-7gfl
    app.kubernetes.io/part-of: tkrw-pr714-0075-0044-app
  name: devfile-sample-7gfl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-7gfl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-7gfl
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0044-tenant/tkrw-pr714-0075-0044-app/devfile-sample-7gfl@sha256:f2fce46e24ba38e0dd102326ebc2c247bc733d5f149f28d735d4a9809fc5c93a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
